apiVersion: apps/v1
kind: Deployment

metadata:
  name: nodeapp
  namespace: nodeapp

spec:
  replicas: 3

  selector:
    matchLabels:
      app: nodeapp

  template:
    metadata:
      labels:
        app: nodeapp

    spec:
      containers:
        - name: nodeapp
          image: argocd-nodejs:1.0
          imagePullPolicy: Never

          ports:
            - containerPort: 3000
